INSERT INTO PERSON
(ID,NAME,LOCATION,BIRTH_DATE)
VALUES(100,'Hany','Canada',sysdate());
INSERT INTO PERSON
(ID,NAME,LOCATION,BIRTH_DATE)
VALUES(101,'John','UK',sysdate());
INSERT INTO PERSON
(ID,NAME,LOCATION,BIRTH_DATE)
VALUES(102,'Mark','US',sysdate());